### ISSUE TITLE
[CHORE] Move all the used icons in `src\components\custom\icons.tsx` and use lucide icons for all

### ISSUE THREAD

**Issue by realChakrawarti** [realChakrawarti/yt-catalog#53]
Currently we are using 2 icons libraries, [react-icons](https://react-icons.github.io/react-icons/) and [lucide icons](https://lucide.dev/icons/). 

It makes sense to use only one since the scope of the project isn't that big. Remove the usage of react-icons and use the alternative or similar ones from lucide. All the icons should be exported from  `src\components\custom\icons.tsx`.

**Comment by jey-exp** [comment]
Your project looks cool, Can I work on it, starting by this issue?

**Comment by realChakrawarti** [comment]
@jey-exp Sure. I assigned the ticket to you. Do fork the repo, and create a PR on the `dev` branch.

Let me know if you are able to setup the project locally or not. 

If you feel there is any pain points when setting it up or even during the development, do let me know. 

Again, thanks for checking it out. Really appreciate it 😃

**Comment by jey-exp** [comment]
Thanks for assigning it. Faced no problem with the local setup. 

Will finish the work and raise a PR on the dev!
