### ISSUE TITLE
[FEATURE] Add "Watch later" functionality

### ISSUE THREAD

**Issue by realChakrawarti** [realChakrawarti/yt-catalog#55]
This feature will allow user to add videos from "Catalog" & "Archive" to "Watch later" page. 

Here are task outline:
- Add another tab "Watch later" alongside "Catalogs' and "Archives" in `/explore` path
- Add an icon signifying "Watch later" in the right most side, similar to description icon on the youtube card
- Clicking on the icon adds the video item in the **localStorage** with the key `watchLater`. The value is an array of object. The object has title, description, channelTitle, videoId, channelLogo and publishedAt.
- Clicking "Watch later" tab redirects to `/watch-later` where data in `watchLater` in **localStorage** gets mapped with youtube card. 
- Add an icon to remove the video from the "Watch later" which removes the item from the **localStorage**.

**Comment by jey-exp** [comment]
Can I get this assigned to me please :) 

I need a quick chat regarding this issue, are you comfortable with discord?

**Comment by jey-exp** [comment]
okay, no problem
But let me clean up the mess I did with the first issue you assigned to me

**Comment by realChakrawarti** [comment]
> okay, no problem But let me clean up the mess I did with the first issue you assigned to me

👍🏽

**Comment by realChakrawarti** [comment]
@jey-exp I hope you are doing good. I retrieved my discord creds 😄, I had created a group for something YouTube related a while back. Here is the link: https://discord.com/invite/e59FzHNtDB.

Let me know if you want to pick up the issue or you can shoot me a DM over discord for any queries related to this.

**Comment by jey-exp** [comment]
> @jey-exp I hope you are doing good. I retrieved my discord creds 
Good to hear that 😄. 

I will pick the issue soon. 
Will see if I can do it now, and ping you in discord for queries.
